version: "3"

networks:
  web:
    external: true

volumes:
  storage:

services:
  backend:
    image: ghcr.io/chaostreff-flensburg/simple-borrow:latest
    restart: always
    volumes:
      - storage:/var/www/html/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ausleihe.rule=Host(`api.bewerben.c3fl.de`)"
      - "traefik.http.routers.ausleihe.entrypoints=https,http"
      - "traefik.http.services.ausleihe.loadbalancer.server.port=80"
      - "traefik.http.routers.ausleihe.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=web"
    working_dir: /var/www/html
    networks:
      - web
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"

  frontend:
    image: ghcr.io/chaostreff-flensburg/simple-borrow:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ausleihe.rule=Host(`bewerben.c3fl.de`)"
      - "traefik.http.routers.ausleihe.entrypoints=https,http"
      - "traefik.http.services.ausleihe.loadbalancer.server.port=80"
      - "traefik.http.routers.ausleihe.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=web"
    networks:
      - web
    logging:
      options:
        max-size: "10m"
