version: "3"

networks:
  web:
    external: true
  stack:

volumes:
  storage:
  database:

services:
  backend:
    image: ghcr.io/chaostreff-flensburg/pretty-good-proposal/backend:latest
    restart: always
    volumes:
      - storage:/var/www/html/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-pgp.rule=Host(`api.bewerben.c3fl.de`)"
      - "traefik.http.routers.api-pgp.entrypoints=https,http"
      - "traefik.http.services.api-pgp.loadbalancer.server.port=80"
      - "traefik.http.routers.api-pgp.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.api.middlewares=cors"
    networks:
      - web
      - stack
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"

  database:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql:cached
    networks:
      - stack
    ports:
      - 127.0.0.1:3306:3306
    env_file:
      - .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=''
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  frontend:
    image: ghcr.io/chaostreff-flensburg/pretty-good-proposal/frontend:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-pgp.rule=Host(`bewerben.c3fl.de`)"
      - "traefik.http.routers.frontend-pgp.entrypoints=https,http"
      - "traefik.http.services.frontend-pgp.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend-pgp.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=web"
    networks:
      - web
    logging:
      options:
        max-size: "10m"
