version: "3"

networks:
  stack:

volumes:
  storage:
  database:

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - storage:/var/www/html/storage
    networks:
      - stack
    env_file:
      - .env
    ports:
      - 8082:80
    logging:
      options:
        max-size: "10m"

  database:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql:cached
    networks:
      - stack
    ports:
      - 127.0.0.1:3366:3306
    env_file:
      - .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=''
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8083:80
    logging:
      options:
        max-size: "10m"
