name: Build and deploy V2

on:
  push:
    branches: ["v2-customize-things"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Frontend
        uses: docker/build-push-action@v3
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: "ghcr.io/${{ github.repository }}/frontend:latest"

      - name: Build Backend
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: "ghcr.io/${{ github.repository }}/backend:latest"

      # - name: pull and start new image
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER_NAME }}
      #     key: ${{ secrets.PRIVATE_KEY}}
      #     script: cd pretty-good-proposal-v2 && docker compose pull && docker compose up -d
